# Generated by Django 5.1.3 on 2024-12-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("summary", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="default/default-user.jpg", upload_to="hero/images"
                    ),
                ),
            ],
        ),
    ]
