# Generated by Django 5.1.3 on 2024-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="default/default-user.jpg", upload_to="hero/images"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=250)),
                ("job_title", models.CharField(max_length=100)),
                ("duties_1", models.CharField(max_length=150)),
                ("duties_2", models.CharField(blank=True, max_length=150, null=True)),
                ("duties_3", models.CharField(blank=True, max_length=150, null=True)),
                ("duties_4", models.CharField(blank=True, max_length=150, null=True)),
                ("technologies_used", models.CharField(max_length=500)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
